- name: create ec2 and route 53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-0b3c1373997970829
    ami_id: ami-0220d79f3f480ecf5
    env: dev
    domain_name: rajkumarns.online
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}"
      tags:
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{env}}"
    loop: "{{ instances }}"
    register: ec2_output
    when: action == create

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
      
  - name: create route53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "roboshop-{{ env }}.{{domain_name}}" #mongodb-dev.rajkumarns.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ ec2_output.results }}"
    when: 
    - item.item == "frontend"
    - action == "create"

  - name: delete ec2 instance
    amazon.aws.ec2_instance:
      state: absent
      name: "{{ item }}-{{env}}"
    loop: "{{ instances }}"



